account/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path("signup", views.Signup.as_view(), name="signup"),
    path("signin", views.Signin.as_view(), name="signin"),
    path("signout", views.Signout.as_view(), name="signout"),
]

blog/urls.py
from django.urls import path

from .import views

urlpatterns = [
    path('', views.BlogList.as_view(), name='blog_list'),
    path('write/new', views.BlogWriteView.as_view(), name='blog_write'),
    path('update/<slug:slug>', views.BlogUpdateView.as_view(), name='blog_update'),
    path('<slug:slug>', views.BlogDetail.as_view(), name='blog_detail'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('pages.urls', 'page'), namespace='page')),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('', include(('account.urls', 'account'), namespace='account')),

    path('', RedirectView.as_view(url='/home', permanent=False)),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pages/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('home', views.HomePage.as_view(), name='home'),
    path('dashboard', views.DashboardView.as_view(), name='dashboard'),
]

account/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.template.defaultfilters import slugify
from django.db import models
from django.contrib.auth.models import User


class BlogPost(models.Model):

    STATUS = (
        (0, 'Draft'),
        (1, 'Publish'),
    )

    title = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(max_length=255, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="blog_posts")
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    published_on = models.DateTimeField(null=True)
    status = models.IntegerField(choices=STATUS, default=0)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs) -> None:
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

account/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class AccountRegisterForm(UserCreationForm):
    email = forms.EmailField()

class Meta:
    model = User
    fields = ['username', 'email']

blog/forms.py
from django import forms

from . import models


class BlogCreationForm(forms.ModelForm):

    class Meta:
        model = models.BlogPost
        fields = ['title', 'content']


class BlogUpdationForm(forms.ModelForm):

    class Meta:
        model = models.BlogPost
        fields = ['title', 'content', 'status']

account/views.py
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import CreateView
from django.urls import reverse_lazy

from . import forms


class Signup(CreateView):
    template_name = "account/signup.html"
    success_url = reverse_lazy("account:signin")
    form_class = forms.AccountRegisterForm


class Signin(LoginView):
    template_name = "account/signin.html"
    redirect_authenticated_user = True # redirect url is handeled in settings.py


class Signout(LogoutView):
    next_page = 'page:home'

blog/views.py
from typing import Any
from django.shortcuts import redirect
from django.utils import timezone
from django.db.models import Q
from django.forms.models import BaseModelForm
from django.http import HttpRequest, HttpResponse
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin

from . import models
from . import forms


class BlogList(ListView):
    template_name = "blog/blog_list.html"
    queryset = models.BlogPost.objects.filter(status=1).order_by('-created_on')
    context_object_name = "blogs"


class BlogDetail(DetailView):
    template_name = "blog/blog_detail.html"
    model = models.BlogPost
    context_object_name = "blog"


class BlogWriteView(LoginRequiredMixin, CreateView):
    template_name = "blog/blog_write.html"
    model = models.BlogPost
    form_class = forms.BlogCreationForm
    success_url = reverse_lazy("page:home")

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.save()
        return super().form_valid(form)


class BlogUpdateView(LoginRequiredMixin, UpdateView):
    template_name = "blog/blog_update.html"
    model = models.BlogPost
    form_class = forms.BlogUpdationForm
    success_url = reverse_lazy("page:dashboard")


    def get(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        slug = Q(slug=kwargs['slug'])
        is_published = Q(status=1)
        if self.model.objects.filter(slug & is_published):
            return redirect("blog:blog_detail", slug=kwargs['slug'])
        return super().get(request, *args, **kwargs)

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.slug = ''

        if self.object.status == 1: # publish
            self.object.published_on = timezone.now()

        self.object.save()
        return super().form_valid(form)

pages/views.py
from typing import Any
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

from blog.models import BlogPost


class HomePage(TemplateView):
    template_name = "pages/home.html"


class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = "pages/dashboard.html"
    login_url = reverse_lazy("account:signin")

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        kwargs = super().get_context_data(**kwargs)
        kwargs['blogs'] = BlogPost.objects.filter(author=self.request.user)
        return kwargs

templates/base.html
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    {% comment %} Font awesome {% endcomment %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" />
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400&display=swap" rel="stylesheet">

    {% comment %} bootstrap css {% endcomment %}
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9"
      crossorigin="anonymous"
    />

    {% comment %} default stylesheet {% endcomment %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />

    {% comment %} for title, link, etc. {% endcomment %}
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>

    {% comment %} navbar {% endcomment %}
    {% block navbar %}{% endblock navbar %}

    {% comment %} Everything goes in here {% endcomment %}
    {% block content %}{% endblock content %}

    {% comment %} bootstrap {% endcomment %}
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
      crossorigin="anonymous"
    ></script>
</body>
</html>

templates/blog/blog_detail.html
{% extends "base.html" %}

{% block title %}{{ object.title }}| Blog{% endblock title %}

{% block navbar %} {% include "navbar.html" with is_authentiated=user.is_authenticated %} {% endblock navbar %}

{% block content %}

<h1>{{ blog.title|capfirst }}</h1>
<p>{{ blog.author|capfirst }} | {{ blog.created_on }}</p>
<p>{{ blog.content|safe }}</p>

{% comment %} <div class="container my-3">
    <div class="row">
        <div class="col-md-8 card mx-auto">
            <div class="card-body">
                <h1 class="card-title">{{ object.title }}</h1>
                <p class="text-muted">{{ post.author|capfirst }} | {{ post.created_on }}</p>
                <p class="card-text">{{ object.content|safe }}</p>
            </div>
        </div>
    </div>
  </div> {% endcomment %}
{% endblock content %}

templates/blog/blog_list.html
{% extends "base.html" %}

{% block title %}All | Blogs{% endblock title %}

{% block navbar %} {% include "navbar.html" with is_authentiated=user.is_authenticated %} {% endblock navbar %}

{% block content %}

{% for blog in blogs %}
<div>
    <h1>{{ blog.title|capfirst }}</h1>
    <p>{{ blog.author|capfirst }} | {{ blog.created_on }}</p>
    <p>{{ blog.content|slice:"220" }}</p>
    <a href="{% url "blog:blog_detail" blog.slug %}">Read More &rarr;</a>
</div>
{% endfor %}

{% comment %} <main class="container">
    <div class="row">
        <div class="col-md-6 mt-3 mx-auto">
            {% for post in post_list %}
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title">{{ post.title|capfirst }}</h2>
                    <p class="card-text text-muted">{{ post.author|capfirst }} | {{ post.created_on }}</p>
                    <p class="card-text">{{ post.content|slice:":220" }}</p>
                    <a href="{% url "blog:blog_detail" post.slug %}" class="btn btn-primary">Read More &rarr;</a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</main> {% endcomment %}
{% endblock content %}

templates/blog/blog_update.html
{% extends "base.html" %}

{% block title %}Update | Blog{% endblock title %}

{% block content %}
<h1>Write your blog</h1>
<form method="post" action="{% url "blog:blog_update" object.slug %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>
{% endblock content %}

templates/blog/blog_write.html
{% extends "base.html" %}

{% block title %}Write | Blog{% endblock title %}

{% block content %}
<h1>Write your blog</h1>
<form method="post" action="{% url "blog:blog_write" %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>
{% endblock content %}

templates/navbar.html
<div>
    <strong>Navbar</strong>
    {% if is_authentiated %}
    <form method="post" action="{% url "account:signout" %}">
        {% csrf_token %}
        <button type="submit">Signout</button>
    </form>
    {% else %}
    <a href="{% url "account:signin" %}">Signin</a>
    {% endif %}
</div>

{% comment %} <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02"
            aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" aria-disabled="true">Disabled</a>
                </li>
            </ul>
            <a href="{% url 'account:logout' %}" class="btn btn-secondary">Signout</a>
        </div>
    </div>
</nav> {% endcomment %}

templates/pages/dashboard.html
{% extends "base.html" %}

{% block title %}Dashboard | Blog{% endblock title %}

{% block content %}
<h1>Dashboard</h1>

<form method="post" action="{% url "account:signout" %}">
    {% csrf_token %}
    <button type="submit">Signout</button>
</form>

<h3>Blogs:</h3>
<ul>
    {% for blog in blogs %}
    <li>
        {% if blog.status == 0 %}
        <strong>
            <a href="{% url "blog:blog_update" blog.slug %}">{{ blog }}</a>
        </strong>
        <p>Draft</p>
        {% else %}
        <strong>
            <a href="{% url "blog:blog_detail" blog.slug %}">{{ blog }}</a>
        </strong>
        <p>Published</p>
        {% endif %}
    </li>
    {% endfor %}
</ul>
{% endblock content %}